95.217.72.119 rs.nintendo.com ms.nintendo-europe.com wiirecommend.nintendo.com.au wii.nintendo.co.jp syscheck.softwii.de
92.222.69.160 gdata.youtube.com
165.227.235.155 nwdsrvwdbctl.nintendo.co.jp nzone001.nintendo-europe.com
195.201.236.139 secure.touchmasterconnect.com
{$HOST_IP} geckocodes.org ccs.cdn.sho.rc24.xyz api.tubefixer.ovh