95.217.77.151 naswii.nintendowifi.net available.gs.nintendowifi.net gs.nintendowifi.net
95.217.77.181 master.gs.nintendowifi.net
178.62.43.212 nas.nintendowifi.net pkvldtprod.nintendo.co.jp ds.pokemon-gl.com en-ds.pokemon-gl.com es-ds.pokemon-gl.com fr-ds.pokemon-gl.com it-ds.pokemon-gl.com ko-ds.pokemon-gl.com
195.201.236.139 peerchat.gs.nintendowifi.net gamestats.gs.nintendowifi.net gamestats2.gs.nintendowifi.net dls1.wiimmfi.de dls1.ilostmymind.xyz
20.104.25.104 pkgdsprod.nintendo.co.jp
78.46.231.155 a.dls1.wiimmfi.de
95.217.72.119 axing.nintendowifi.net