# Recommended Sites - Internet Channel
address=/rs.nintendo.com/95.217.72.119
address=/ms.nintendo-europe.com/95.217.72.119
address=/wiirecommend.nintendo.com.au/95.217.72.119
address=/wii.nintendo.co.jp/95.217.72.119

# Please ignore
address=/gdata.youtube.com/92.222.69.160
address=/syscheck.softwii.de/95.217.72.119
address=/nwdsrvwdbctl.nintendo.co.jp/165.227.235.155
address=/nzone001.nintendo-europe.com/165.227.235.155
address=/geckocodes.org/HOST_IP
address=/secure.touchmasterconnect.com/195.201.236.139
address=/ccs.cdn.sho.rc24.xyz/HOST_IP
address=/api.tubefixer.ovh/HOST_IP