# WiiLink
address=/cfh.wapp.wii.com/HOST_IP
address=/ente.wapp.wii.com/HOST_IP
address=/entj.wapp.wii.com/HOST_IP
address=/entu.wapp.wii.com/HOST_IP
address=/miicontest.wapp.wii.com/HOST_IP
address=/miicontestp.wapp.wii.com/HOST_IP
address=/news.wapp.wii.com/HOST_IP
address=/nwcs.wapp.wii.com/95.217.72.119
address=/vt.wapp.wii.com/HOST_IP
address=/weather.wapp.wii.com/HOST_IP
address=/wus.wapp.wii.com/95.217.72.119
address=/conntest.nintendowifi.net/HOST_IP