# Wiimmfi
address=/gamespy.com/95.217.77.151
server=/naswii.nintendowifi.net/95.217.77.151
address=/nas.nintendowifi.net/178.62.43.212
address=/available.gs.nintendowifi.net/95.217.77.151
address=/master.gs.nintendowifi.net/95.217.77.181
server=/sake.gs.nintendowifi.net/95.217.77.151
server=/race.gs.nintendowifi.net/95.217.77.151
address=/peerchat.gs.nintendowifi.net/195.201.236.139
address=/pkgdsprod.nintendo.co.jp/20.104.25.104
address=/pkvldtprod.nintendo.co.jp/178.62.43.212
address=/ds.pokemon-gl.com/178.62.43.212
address=/en-ds.pokemon-gl.com/178.62.43.212
address=/es-ds.pokemon-gl.com/178.62.43.212
address=/fr-ds.pokemon-gl.com/178.62.43.212
address=/it-ds.pokemon-gl.com/178.62.43.212
address=/ko-ds.pokemon-gl.com/178.62.43.212
address=/gamestats.gs.nintendowifi.net/195.201.236.139
address=/gamestats2.gs.nintendowifi.net/195.201.236.139
# server=/sake.gamespy.com/95.217.77.151
address=/sake.gamespy.com/78.46.231.155
address=/gs.nintendowifi.net/95.217.77.151
address=/a.dls1.wiimmfi.de/78.46.231.155
address=/dls1.wiimmfi.de/195.201.236.139
address=/dls1.ilostmymind.xyz/195.201.236.139
address=/axing.nintendowifi.net/95.217.72.119

##NUTMEG
server=/natneg1.gs.nintendowifi.net/95.217.77.151
server=/natneg2.gs.nintendowifi.net/95.217.77.151
server=/natneg3.gs.nintendowifi.net/95.217.77.151
server=/natneg4.gs.nintendowifi.net/95.217.77.151
server=/natneg5.gs.nintendowifi.net/95.217.77.151
server=/natneg6.gs.nintendowifi.net/95.217.77.151
