naswii.nintendowifi.net sake.gs.nintendowifi.net race.gs.nintendowifi.net natneg1.gs.nintendowifi.net natneg2.gs.nintendowifi.net natneg3.gs.nintendowifi.net natneg4.gs.nintendowifi.net natneg5.gs.nintendowifi.net natneg6.gs.nintendowifi.net {
    forward . 95.217.77.151
}