# Kaeru DNS
flipnote.hatena.com maintenance.hatena.ne.jp ugo.hatena.ne.jp ugomemo.hatena.ne.jp {
    template IN A {
        answer "{{ .Name }} 60 IN A 178.62.43.212"
    }
    template IN ANY {
        rcode NOERROR
    }
    log
    errors
}