# Recommended sites (redirected to bookmarks.wiilink.ca)

rs.nintendo.com ms.nintendo-europe.com wiirecommend.nintendo.com.au wii.nintendo.co.jp {
    template IN A {
        answer "{{ .Name }} 60 IN A {$HOST_IP}"
    }
    template IN ANY {
        rcode NOERROR
    }
    log
    errors
}

nwdsrvwdbctl.nintendo.co.jp nzone001.nintendo-europe.com {
    template IN A {
        answer "{{ .Name }} 60 IN A 165.227.235.155"
    }
    template IN ANY {
        rcode NOERROR
    }
    log
    errors
}

secure.touchmasterconnect.com {
    template IN A {
        answer "{{ .Name }} 60 IN A 195.201.236.139"
    }
    template IN ANY {
        rcode NOERROR
    }
    log
    errors
}

geckocodes.org ccs.cdn.sho.rc24.xyz api.tubefixer.ovh {
    template IN A {
        answer "{{ .Name }} 60 IN A {$HOST_IP}"
    }
    template IN ANY {
        rcode NOERROR
    }
    log
    errors
}