# Official WiiConnect24 domains, redirected to us
cfh.wapp.wii.com ente.wapp.wii.com entj.wapp.wii.com entu.wapp.wii.com miicontest.wapp.wii.com miicontestp.wapp.wii.com news.wapp.wii.com vt.wapp.wii.com weather.wapp.wii.com conntest.nintendowifi.net {
    template IN A {
        answer "{{ .Name }} 60 IN A {$HOST_IP}"
    }
    template IN ANY {
        rcode NOERROR
    }
    log
    errors
}