(
    # cfh: Used to insert custom EULA
    cfh.wapp.wii.com
    # miicontest: Used for Check Mii Out / Mii Contest Channel data in Wii Sports Resort
    miicontest.wapp.wii.com
    # conntest: Used for internet connection test
    conntest.nintendowifi.net
    # Recommended sites: Used for recommended sites bookmark in Internet Channel
    wii-links.nintendo-europe.com rs.nintendo.com ms.nintendo-europe.com wiirecommend.nintendo.com.au wii.nintendo.co.jp
) {
    template IN A {
        answer "{{ .Name }} 60 IN A {$HOST_IP}"
    }
    template IN ANY {
        rcode NOERROR
    }
    log
    errors
}