naswii.nintendowifi.net sake.gs.nintendowifi.net race.gs.nintendowifi.net natneg1.gs.nintendowifi.net natneg2.gs.nintendowifi.net natneg3.gs.nintendowifi.net natneg4.gs.nintendowifi.net natneg5.gs.nintendowifi.net natneg6.gs.nintendowifi.net {
    forward . 95.217.77.151
    log
    errors
}

gamespy.com available.gs.nintendowifi.net gs.nintendowifi.net {
    template IN A {
        answer "{{ .Name }} 60 IN A 95.217.77.151"
    }
    template IN ANY {
        rcode NOERROR
    }
    log
    errors
}

nas.nintendowifi.net pkvldtprod.nintendo.co.jp ds.pokemon-gl.com en-ds.pokemon-gl.com es-ds.pokemon-gl.com fr-ds.pokemon-gl.com it-ds.pokemon-gl.com ko-ds.pokemon-gl.com {
    template IN A {
        answer "{{ .Name }} 60 IN A 178.62.43.212"
    }
    template IN ANY {
        rcode NOERROR
    }
    log
    errors
}

master.gs.nintendowifi.net {
    template IN A {
        answer "{{ .Name }} 60 IN A 95.217.77.181"
    }
    template IN ANY {
        rcode NOERROR
    }
    log
    errors
}

peerchat.gs.nintendowifi.net gamestats.gs.nintendowifi.net gamestats2.gs.nintendowifi.net dls1.wiimmfi.de dls1.ilostmymind.xyz {
    template IN A {
        answer "{{ .Name }} 60 IN A 195.201.236.139"
    }
    template IN ANY {
        rcode NOERROR
    }
    log
    errors
}

pkgdsprod.nintendo.co.jp {
    template IN A {
        answer "{{ .Name }} 60 IN A 20.104.25.104"
    }
    template IN ANY {
        rcode NOERROR
    }
    log
    errors
}

sake.gamespy.com a.dls1.wiimmfi.de {
    template IN A {
        answer "{{ .Name }} 60 IN A 78.46.231.155"
    }
    template IN ANY {
        rcode NOERROR
    }
    log
    errors
}

axing.nintendowifi.net {
    template IN A {
        answer "{{ .Name }} 60 IN A 95.217.72.119"
    }
    template IN ANY {
        rcode NOERROR
    }
    log
    errors
}