naswii.nintendowifi.net gs.nintendowifi.net gamespy.com nas.nintendowifi.net pkvldtprod.nintendo.co.jp pokemon-gl.com pkgdsprod.nintendo.co.jp axing.nintendowifi.net {
    forward . 95.217.77.151
    log
    errors
}

# all in dns match
#gamespy.com available.gs.nintendowifi.net gs.nintendowifi.net {
#    template IN A {
#        answer "{{ .Name }} 60 IN A 95.217.77.151"
#    }
#    template IN ANY {
#        rcode NOERROR
#    }
#    log
#    errors
#}

# all in dns match besides nas(?)
# has redirect to 78.46.231.155, possible ours is outdated
#nas.nintendowifi.net pkvldtprod.nintendo.co.jp ds.pokemon-gl.com en-ds.pokemon-gl.com es-ds.pokemon-gl.com fr-ds.pokemon-gl.com it-ds.pokemon-gl.com ko-ds.pokemon-gl.com {
#    template IN A {
#        answer "{{ .Name }} 60 IN A 178.62.43.212"
#    }
#    template IN ANY {
#        rcode NOERROR
#    }
#    log
#    errors
#}

# dns returns 95.217.77.1**5**1
#master.gs.nintendowifi.net {
#    template IN A {
#        answer "{{ .Name }} 60 IN A 95.217.77.181"
#    }
#    template IN ANY {
#        rcode NOERROR
#    }
#    log
#    errors
#}

# all in dns match besides dls1.wiimmfi.de (188.34.177.217)
# indeed, dls1 for both domains are not overridden in their dns
#peerchat.gs.nintendowifi.net gamestats.gs.nintendowifi.net gamestats2.gs.nintendowifi.net dls1.wiimmfi.de dls1.ilostmymind.xyz {
#    template IN A {
#        answer "{{ .Name }} 60 IN A 195.201.236.139"
#    }
#    template IN ANY {
#        rcode NOERROR
#    }
#    log
#    errors
#}

# matches in dns
#pkgdsprod.nintendo.co.jp {
#    template IN A {
#        answer "{{ .Name }} 60 IN A 20.104.25.104"
#    }
#    template IN ANY {
#        rcode NOERROR
#    }
#    log
#    errors
#}

# sake.gamespy.com appears to be absent from dns
# a.dls1.wiimmfi.de doesn't need an override
#sake.gamespy.com a.dls1.wiimmfi.de {
#    template IN A {
#        answer "{{ .Name }} 60 IN A 78.46.231.155"
#    }
#    template IN ANY {
#        rcode NOERROR
#    }
#    log
#    errors
#}

# dns returns 69.25.139.140
#axing.nintendowifi.net {
#    template IN A {
#        answer "{{ .Name }} 60 IN A 95.217.72.119"
#    }
#    template IN ANY {
#        rcode NOERROR
#    }
#    log
#    errors
#}