name: Validate NGINX config

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Validate NGINX config
      run: |
       docker run --rm \
       --entrypoint "/usr/sbin/nginx" \
       -v ./nginx/templates:/etc/nginx/templates \
       -v ./nginx/default.conf:/etc/nginx/conf.d/default.conf \
       -it nginx:alpine -t